version: "3"
services:
  pg:
    image: postgres:alpine
    volumes:
      - $DB_DATA:/var/lib/postgresql/data
    ports:
      - "$DB_PORT:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    restart: always
    #   networks:
    #  - backend
  vertex-sample:
    image: jeanlopes/vertx-sample:SNAPSHOT
    links:
      - pg
    ports:
      - "$HTTP_SERVER_PORT:$HTTP_SERVER_PORT"
    environment:
      - HTTP_SERVER_PORT
      - HTTP_SERVER_INSTANCES
      - DB_JDBC
      - DB_USER
      - DB_PASS
      - DB_MAX_POOL_SIZE
    restart: always
    # networks:
    #   - backend
    # networks:
    #   backend:
    #     driver: "bridge"
